### ISSUE TITLE
Curseforge Release Link is Broken

### ISSUE THREAD

**Issue by FlyGuyGo** [ReillyGregorio/MobScarecrow#1]
The Curseforge release link on the main page leads to a Github 404 error. I am having trouble identifying which scare crow mod is yours.

**Comment by ArcanePigeon** [comment]
Could you provide more information on what the problem you are having is? I would also recommend asking these questions on the discord where I can see your messages reply faster.

**Comment by FlyGuyGo** [comment]
I am referring to the main GitHub page for this project. The Curseforge link is broken (see photo below) and I am not sure which project on Curseforge is yours. Also what is the link to your server?
![24B7B7D8-8848-4925-916C-FC2071EB667E](https://user-images.githubusercontent.com/85654654/149573383-6dc70883-1a7d-4a68-8ada-febb892ce4d0.jpeg)

**Comment by ArcanePigeon** [comment]
I updated the link in the readme. The project on curseforge is just called mob scarecrows and has an icon with a purple background and a scarecrow and plushies around it. If you are referring to a minecraft server, there is not one. If you mean a discord server the link is on the curseforge page.
