### ISSUE TITLE
Heavy TPS Load on my server

### ISSUE THREAD

**Issue by TheButterbrotMan** [ReillyGregorio/MobScarecrow#10]
https://spark.lucko.me/W7TtUawMOc?hl=164

**Comment by ArcanePigeon** [comment]
this issue has been fixed. The change will be available in the next update.

**Comment by TheButterbrotMan** [comment]
Are you maybe able to push this update soon? My server is really suffering :(

**Comment by ArcanePigeon** [comment]
I am currently busy with something that takes higher priority but the update should be out either this week or next week. I recommend just disabling the mod for now or setting the scare radius to 0 to reduce lag.
