### ISSUE TITLE
High MSPT impact

### ISSUE THREAD

**Issue by greyivy** [ReillyGregorio/MobScarecrow#2]
This mod was causing some performance issues on my server, specifically in `org.cloudwarp.mobscarecrow.goals.EntityUtils.findNearestScarecrow()`.

Profile: https://spark.lucko.me/z0P0CuAAU8

**Comment by ArcanePigeon** [comment]
Have you updated to the latest version 1.1.0?

**Comment by greyivy** [comment]
Totally should've checked that. Works beautifully now, thanks for the lovely mod!
