### ISSUE TITLE
Gamerule fix

### ISSUE THREAD

**Issue by itsdinkd** [ReillyGregorio/MobScarecrow#3]
Can you release your server gamerule fix on 1.18.1? I will not be updating my modpack to 1.18.2 due to all the issues with it, but would love this fix so people can properly use MobScarecrows if they do not know about the work around

**Comment by ArcanePigeon** [comment]
I will look into making it work for 1.18.1. Hopefully I should just be able to change the required version in the settings and make it function for both versions.
